language: ruby
cache: bundler
rvm:
  - 2.4.0

before_install:
  - gem install bundler
  - gem cleanup minitest
  - gem cleanup rake
  - bundle install --without production
  - rake db:drop
  - rake db:create
  - rake db:reset
  - rake db:migrate

script: bundle exec cucumber